server:
  port: 8080

spring:
  datasource:
    url: ${B2_DB_URL:jdbc:postgresql://localhost:5432/b2_database}
    username: ${B2_DB_USER:b2_user}
    password: ${B2_DB_PASS:b2pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info